### PR TITLE
Better exceptions message

### PR DESCRIPTION
**Pull request by K07H**
Most of the time you don't get any useful information from the Exception but instead you get some from the InnerException. I use this all the time and I was wondering why it's not there already as it really helps to track down issues.

### CODE REVIEW

**Comment by PrimeSonic** [comment]
Better option is to simply use the exception's `ToString` method.
All the Exception is written and labeled  with ToString().

**Comment by K07H** [comment]
You don't have inner exception with ToString.

**Comment by K07H** [comment]
When I have a bug at SMLHelper level I don't have any useful information from the log.
This modification allows me to know why SMLHelper failed and to fix my code accordingly

**Comment by PrimeSonic** [comment]
The default `ToString` also calls ToString on the InnerException if one exits.
https://msdn.microsoft.com/en-us/library/system.exception.tostring%28v=vs.90%29.aspx
```The default implementation of ToString obtains the name of the class that threw the current exception, the message, the result of calling ToString on the inner exception, and the result of calling Environment.StackTrace. If any of these members is null, its value is not included in the returned string.```

**Comment by ahk1221** [comment]
Have to change the brackets, I don't like them imo, but accepting since I have to go

**Comment by K07H** [comment]
You don't get InnerException details with ToString.
That's the only way to get full information.
@PrimeSonic

**Pull request merged**
