### PR TITLE
Added possibility to make a TechType compatible with bioreactors.

### PR DESCRIPTION
**Pull request by K07H**
1. Added possibility to make a TechType compatible with bioreactors.
2. Modified description of the "custom inventory background type" capability to make it more clear.

### CODE REVIEW

**Comment by AlexejheroYTB** [comment]
Thats exactly what Ive been doing for the last 48 hours on my mod :D

**Comment by K07H** [comment]
You patch this dictionary for the last 48hours? What techtypes did you add to it? :P

**Comment by AlexejheroYTB** [comment]
No. Just for the last 30 minutes. But the ideea came to me 48 hours ago.

**Comment by AlexejheroYTB** [comment]
:3

**Comment by K07H** [comment]
I did it 48hours ago too for the new flora, But I decided to PR it.

**Comment by AlexejheroYTB** [comment]
I tried to patch the dictionary in the constructor, but i found it hard to patch static constructors, so i just did it in the OnHover method

**Comment by K07H** [comment]
You don't need to patch any function for that.
You can patch attributes directly.

**Comment by AlexejheroYTB** [comment]
Yes but I want to patch them in every instance of a class. Even existing ones. And the class constructor changes the field

**Comment by K07H** [comment]
No it's a static attribute. There's only one.

**Comment by AlexejheroYTB** [comment]
Oh.

**Comment by AlexejheroYTB** [comment]
I did not know it was statit

**Comment by K07H** [comment]
RIP x)

**Comment by AlexejheroYTB** [comment]
Anyway, do i just change it with reflection?

**Comment by AlexejheroYTB** [comment]
And write null where i should put the instance?

**Comment by AlexejheroYTB** [comment]
I _think_ thats how its done

**Pull request merged**
