### PR TITLE
Cosmethics

### PR DESCRIPTION
**Pull request by K07H**
AHK don't like brackets x)
I think it's better to use them so you can easily spot blocks of information, but w/e.

### CODE REVIEW

**Comment by AlexejheroYTB** [comment]
Cosmetics*

**Comment by K07H** [comment]
Can't you just learn french instead of coming after me to quote lmao

**Comment by K07H** [comment]
You'd better use your knowledge to go fix this if I made mistakes lol
https://raw.githubusercontent.com/K07H/DecorationsMod/master/translation_template.txt

**Comment by AlexejheroYTB** [comment]
*Spelling *Nazi
Grammar is something else
:3

**Comment by AlexejheroYTB** [comment]
Ill check the file. If i see any errors ill fork and pull request

**Pull request merged**
