### PR TITLE
2.0.OSubMarin - Additional checked for PreRegistered TechTypes and CraftTreeTypes

### PR DESCRIPTION
**Pull request by PrimeSonic**
`CraftTreeTypePatcher` and `TechTypePatcher` now have an additional layer of collision protection against pre-registered IDs from other mods.

While not 100% effective given the possible race conditions, this does still offer one more safety net that can be used along side the hard-coded ban list and the external ban list.

### CODE REVIEW

**Comment by ahk1221** [comment]
Are SortedLists really a good idea? I don't really know much about them, but a quick Google search tells me that its some kind of dictionary. Max() should return the largest value.

**Comment by PrimeSonic** [comment]
Right, I should be calling Last instead of Max if I want the benefit I was going for.
That being, getting the largest index in a single operation instead of having to crawl the whole list each time.

**Comment by ahk1221** [comment]
Nice!

**Comment by ahk1221** [comment]
(Sorry, misclick)

**Pull request merged**
